# 공통 설정 및 로컬 환경
app:
  upload:
    root-dir: /upload

server:
  tomcat:
    max-http-form-post-size: 2MB
    max-swallow-size: 2MB

spring:
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
      resolve-lazily: true

  profiles:
    active: local # 기본 프로필은 로컬로 설정

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false # 로컬 개발 시에는 캐시 끔

---
# 서버(EC2/배포) 환경 설정
spring:
  config:
    activate:
      on-profile: prod
  
  # GitHub Secrets와 .env를 통해 주입받는 환경변수
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: root
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false

  thymeleaf:
    cache: true # 서버 성능을 위해 캐시 활성화

logging:
  level:
    root: info
    org.hibernate.SQL: info