version: "3.8"

services:
  mysql:
    image: mysql:8.0.43
    container_name: pb-mysql-local
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: pb
      MYSQL_USER: pbuser
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
      TZ: Asia/Seoul
    ports:
      - "3307:3306"
    volumes:
      - pb_mysql_data:/var/lib/mysql
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_0900_ai_ci"]

volumes:
  pb_mysql_data:
